[team7_pair1] Step4 구현 완료하였습니다. 코드리뷰 부탁드립니다!!
wwh-techcamp-2018/baeminchan pull request #59
Opened 2018-08-06 11:51 UTC by quodvide

- BestCategory, Brand, SideDish, SideDishImage, DeliveryType 구현
- BestCategory 리스트를 가져오는 Api구현 및 테스트구현
- 프론트엔드 template literal, event deligation등 사용하여 구현
- Ehcache를 Promotion, BestCategory에 적용

2018-08-06 12:24 UTC, javajigi approved these changes
cache 구현 잘 했네요. 👍 
BE 승인합니다.

2018-08-06 12:46 UTC, nigayo commented
deligation => delegation

2018-08-06 12:46 UTC, nigayo commented
Api => API (모두 약자이니까)

2018-08-06 12:53 UTC, crongro requested changes
약간 개선을 하고 넘어가면 더 좋겠습니다.
:-)

2018-08-06 12:53 UTC, nigayo commented on src/main/resources/static/js/categories.js
> +         bestcategory.sideDishes.forEach(function(sideDish) {
중첩된 코드가 됐는데요. 함수라도 분리하면 조금더 보기는 좋을 거 같네요.
```
function makeSideDishHTML(sideDish) {....}
bestcategory.sideDishes.forEach(makeSideDishHTML);
```

2018-08-06 12:53 UTC, nigayo commented on src/main/resources/static/js/categories.js
> +function drawBestCategories() {
draw? 화면에 내용을 채우는거라면 render라는 표현을 더 자주 써요.
draw는 시각화된 정보를 그리는 걸로 다들 예상할겁니다.

2018-08-06 12:53 UTC, nigayo commented on src/main/resources/static/js/categories.js
> +    Array.from($('#bestCategorySideDishBox').children).map(child => child.classList.remove("on"));
배열로 바꾸기도 하고 잘했네요. 
map 은 잘 못된 사용이에요.
map이 뜻하는 것이 무엇인지 확인하고, 반환하는 값이 무엇인지도 확인해보세요.

javascript의  interation 표준 방법은 무엇인지도 고민해서 적용해보세요.

2018-08-07 01:06 UTC, merged

2018-08-07 01:47 UTC, nigayo commented
네  FE  확인했습니다. 수고했어요~! 
@quodvide