[Team8_pair1] Step4 중간완료
wwh-techcamp-2018/baeminchan pull request #62
Opened 2018-08-06 13:16 UTC by Mia6111

백엔드에서 반찬, 베스트반찬 카테고리 생성
프론트에서 Ajax통신으로 데이터 받아온후 렌더링 및 이벤트리스너 추가했습니다.
Spring cacheable 은 아직 하지 않았습니다. 코드리뷰 부탁드려요!

2018-08-06 13:51 UTC, javajigi requested changes
피드백 하나 남겨요. cache 적용한 후 다시 피드백 할께요.

2018-08-06 13:51 UTC, javajigi commented on src/main/java/codesquad/domain/Banchan.java
> +    private String title;
title null 허용인가요?
각 column 설정을 좀 더 철저히 하면 좋을 것 같아요.

2018-08-06 21:31 UTC, crongro approved these changes
fe코드가 부쩍 좋아졌네요.

2018-08-06 21:31 UTC, nigayo commented on src/main/resources/static/js/best.js
> +    const randomIdx = Math.floor(Math.random()*6);
6숫자보다는 dom의 갯수를 확인해서 동적으로 값을 할당하는게 나을 듯.

2018-08-06 21:31 UTC, nigayo commented on src/main/resources/static/js/best.js
> +    await initBestCategory();
맙 to the 소사.
async/await 적용을 이해했나요? 
멋집니다. 동작에 대해서 잘 알아두세요. 현재 가장 많이 쓰는 방법이에요.

2018-08-06 21:31 UTC, nigayo commented on src/main/resources/static/js/best.js
> +    index = index || "";
defaultparameter 가 무엇인지 찾아서 이런경우 수정해보세요.

2018-08-06 21:31 UTC, nigayo commented on src/main/resources/static/js/common.js
> +const fetchAsync = ({ url, method, body, headers} ) => (
common.js 는 좋습니다.
프로젝트에서도 쓸 수 있도록 계속 범용적인 함수로 발전시켜보세요.

2018-08-06 21:31 UTC, nigayo commented on src/main/resources/static/js/best.js
> +const banchanInit = (data, id) => {
함수이름은 늘 동사+명사로 '의도'를 잘 드러내세요.

2018-08-06 21:31 UTC, nigayo commented on src/main/resources/static/js/best.js
> +    const html = data.reduce( (accum, cur) => {
reduce 사용 잘 했음.

2018-08-07 11:21 UTC, mia6111 commented
- 백엔드 캐시 적용 및 도메인 Annotation 추가
- 프론트 기존 버그 수정

코드 리뷰 부탁드립니다 :-)

2018-08-07 12:03 UTC, javajigi approved these changes
Cache 관련 피드백 하나 남겼어요.

2018-08-07 12:03 UTC, javajigi commented on src/main/java/codesquad/service/BestBanchanService.java
> +    @Cacheable("banchan")
Cache 데이터에 변경이 발생할 경우 Cache를 무효화하기 위해 CacheEvict이라는 설정을 사용할 수 있어요.
이와 관련한 학습하고 추후 적용해 보세요.

2018-08-07 12:03 UTC, merged